config/routes.rb
Rails.application.routes.draw do
  resources :gifts do
    collection do
      get :giftmash
      get :results
    end
    member do
      patch :upvote
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "gifts#giftmash"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gift.rb
class Gift < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: %i[ show edit update destroy upvote ]

  def giftmash
    @random_gifts = Gift.where(id: [*Gift.minimum(:id)..Gift.maximum(:id)].sample(2))
  end

  def results
    @gifts = Gift.all.order(upvotes: :desc, downvotes: :asc)
  end

  # GET /gifts or /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1 or /gifts/1.json
  def show
  end

  # UPVOTE THE GIFTS
  def upvote
    @gift.update!(upvotes: @gift.upvotes += 1)
    downvoted_gift = Gift.find(params[:downvoted_gift_id])
    downvoted_gift.update!(downvotes: downvoted_gift.downvotes += 1)
    redirect_to giftmash_gifts_path
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts or /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: "Gift was successfully created." }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1 or /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: "Gift was successfully updated." }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1 or /gifts/1.json
  def destroy
    @gift.destroy!

    respond_to do |format|
      format.html { redirect_to gifts_path, status: :see_other, notice: "Gift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gift_params
      params.require(:gift).permit(:name, :image_url, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_with(model: gift) do |form| %>
  <% if gift.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
        <% gift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gifts/_gift.html.erb
<div id="<%= dom_id gift %>">
  <p>
    <strong>Name:</strong>
    <%= gift.name %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= gift.image_url %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= gift.url %>
  </p>

</div>

app/views/gifts/edit.html.erb
<% content_for :title, "Editing gift" %>

<h1>Editing gift</h1>

<%= render "form", gift: @gift %>

<br>

<div>
  <%= link_to "Show this gift", @gift %> |
  <%= link_to "Back to gifts", gifts_path %>
</div>

app/views/gifts/giftmash.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Gifts" %>

<div class="top-bar">
  <div></div>
  <h3 class="giftmash-heading">Giftmash</h3>
  <%= link_to 'RESULTS', results_gifts_path, class: 'top-link' %>
</div>


<h1 class="center-heading">What do you like better?</h1>

<div class="gifts-loader" id="gifts-loader"></div>
<div id="overlay" class="overlay"></div>

<div class="gifts-container" data-controller="giftmash">
  <% @random_gifts.each do |gift| %>
    <div class="gift-card">
      <%= gift.name %>
      <%= image_tag gift.image_url %>
      <%= button_to "LIKE", upvote_gift_path(gift, downvoted_gift_id: gift == @random_gifts.first ? @random_gifts.last.id : @random_gifts.first.id), 
                                          method: :patch, class: 'like-button', 
                                          data: { turbo: false, action: "click->giftmash#showLoader"} %>
    </div>
  <% end %>
</div>

<div class="skip-button">
  <%= link_to 'SKIP', giftmash_gifts_path, class: 'skip-link' %>
</div>

app/views/gifts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Gifts" %>

<h1>Gifts</h1>

<div id="gifts">
  <% @gifts.each do |gift| %>
    <%= render gift %>
    <p>
      <%= link_to "Show this gift", gift %>
    </p>
  <% end %>
</div>

<%= link_to "New gift", new_gift_path %>

app/views/gifts/new.html.erb
<% content_for :title, "New gift" %>

<h1>New gift</h1>

<%= render "form", gift: @gift %>

<br>

<div>
  <%= link_to "Back to gifts", gifts_path %>
</div>

app/views/gifts/results.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Results" %>


<div class="results-top-bar">
  <div></div>
  <%= link_to 'Giftmash', giftmash_gifts_path %>
  <h4 class="results-heading">Results</h4>
</div>

<h1 class="center-heading">Results</h1>
<h3 class="below-center-heading">The Best Gifts</h3>

<table class="results-table">
  <thead>
    <tr>
      <th>Gift Name</th>
      <th>Upvotes</th>
      <th>Downvotes</th>
    </tr>
  </thead>
  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.name %></td>
        <td><%= gift.upvotes %></td>
        <td><%= gift.downvotes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gifts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gift %>

<div>
  <%= link_to "Edit this gift", edit_gift_path(@gift) %> |
  <%= link_to "Back to gifts", gifts_path %>

  <%= button_to "Destroy this gift", @gift, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Giftmash" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>